apiVersion: v1
kind: Service
metadata:
  name: sp-service-load-balancer
  labels:
    service: sp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: sp-app
